name: Windows Release

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@v1
      with:
        components: rustfmt, clippy
        toolchain: 1.83.0
    - name: Build
      run: |
        cargo build --release
    - name: Upload binary
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/fluyendo
        asset_name: fluyendo-${{ matrix.os }}
        tag: ${{ github.ref }}
